# To use:
#  pre-commit install

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: trailing-whitespace
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
-   repo: local
    hooks:
    -   id: cargo-test
        name: cargo test
        entry: cargo test --release
        language: rust
        pass_filenames: false
